media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "essays"
    label: "Essays"
    folder: "content/_essays"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "books"
    label: "Books"
    folder: "content/_books"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "concepts"
    label: "Concepts"
    folder: "content/_concepts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Concept", name: "concept", widget: "string" }
      - { label: "Discipline", name: "discipline", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "values"
    label: "Values"
    folder: "content/_values"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "authors"
    label: "Authors"
    folder: "content/_authors"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "journal"
    label: "Journal"
    folder: "content/_journal"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
